// ============================================
// Card Registry - Complete catalog of all 79 cards
// ============================================

import {
  CardRegistration,
  CardCategory,
  LicenseTier,
  CardStatus,
} from '../models/CardCatalog';

export const CARD_REGISTRY: CardRegistration[] = [
  // ═══════════════════════════════════════════
  // IMMEDIATE ACTION (10 cards)
  // ═══════════════════════════════════════════
  {
    id: 'stale-conversations',
    catalogNumber: 1,
    name: 'Stale Conversations',
    category: CardCategory.ImmediateAction,
    impactRating: 10,
    minimumTier: LicenseTier.Individual,
    status: CardStatus.Implemented,
    existingCardId: 'waitingOnYou',
    description: "Teams chats/emails where you're the last blocker",
    keyValue: 'Surfaces invisible accountability — people waiting on you',
    intelligenceEnrichment: 'Predicts escalation risk, drafts responses',
    dataSources: ['Mail API', 'Teams Chat API', 'Teams Channel API'],
    tags: ['email', 'teams', 'urgency', 'accountability'],
  },
  {
    id: 'approval-bottlenecks',
    catalogNumber: 2,
    name: 'Approval Bottlenecks',
    category: CardCategory.ImmediateAction,
    impactRating: 9,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: "Approvals you're holding up, sorted by wait time",
    keyValue: 'Direct productivity unlock for others',
    intelligenceEnrichment: 'Predicts downstream delays, suggests delegation',
    dataSources: ['Approvals API', 'Power Automate API'],
    tags: ['approvals', 'blocking', 'urgency'],
  },
  {
    id: 'my-urgent-items',
    catalogNumber: 3,
    name: 'My Urgent Items',
    category: CardCategory.ImmediateAction,
    impactRating: 9,
    minimumTier: LicenseTier.Individual,
    status: CardStatus.Implemented,
    existingCardId: 'unreadInbox',
    description: 'Tasks, approvals, @mentions from last 24 hours',
    keyValue: 'Cuts through noise to what actually needs attention',
    intelligenceEnrichment: 'AI priority scoring, smart triage suggestions',
    dataSources: ['Mail API', 'Teams API', 'Planner API', 'To Do API'],
    tags: ['triage', 'urgency', 'daily-review'],
  },
  {
    id: 'broken-promises',
    catalogNumber: 4,
    name: 'Broken Promises',
    category: CardCategory.ImmediateAction,
    impactRating: 9,
    minimumTier: LicenseTier.Individual,
    status: CardStatus.Implemented,
    existingCardId: 'flaggedEmails',
    description: 'Tasks/commitments from emails/chats now overdue',
    keyValue: "Credibility protection — tracks what you said you'd do",
    intelligenceEnrichment: 'Sentiment-aware urgency, auto-drafts follow-up',
    dataSources: ['Mail API', 'Teams Chat API', 'Planner API'],
    tags: ['commitments', 'credibility', 'overdue'],
  },
  {
    id: 'meeting-prep',
    catalogNumber: 5,
    name: 'Meeting Prep',
    category: CardCategory.ImmediateAction,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'todaysAgenda',
    description: 'Agenda items, files, recent comms for next 3 meetings',
    keyValue: 'Reduces meeting waste, signals preparedness',
    intelligenceEnrichment: 'AI-generated briefing notes, sentiment context',
    dataSources: ['Calendar API', 'Mail API', 'OneDrive API'],
    tags: ['meetings', 'preparation', 'calendar'],
  },
  {
    id: 'unread-from-vips',
    catalogNumber: 6,
    name: 'Unread from VIPs',
    category: CardCategory.ImmediateAction,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'email',
    description: 'Messages from manager, directs, pinned contacts',
    keyValue: 'Relationship prioritisation at scale',
    intelligenceEnrichment: 'Sentiment detection, urgency prediction',
    dataSources: ['Mail API', 'People API'],
    tags: ['vip', 'prioritisation', 'relationships'],
  },
  {
    id: 'pre-meeting-conflicts',
    catalogNumber: 7,
    name: 'Pre-Meeting Conflicts',
    category: CardCategory.ImmediateAction,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Double-bookings or back-to-back with no transition',
    keyValue: 'Prevents the scramble, protects focus time',
    dataSources: ['Calendar API'],
    tags: ['calendar', 'conflicts', 'scheduling'],
  },
  {
    id: 'waiting-on-external',
    catalogNumber: 8,
    name: 'Waiting on External',
    category: CardCategory.ImmediateAction,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'waitingOnOthers',
    description: 'External emails with no response in 5+ days',
    keyValue: 'Deal/project momentum maintenance',
    dataSources: ['Mail API'],
    tags: ['external', 'follow-up', 'waiting'],
  },
  {
    id: 'contextual-action-suggestions',
    catalogNumber: 66,
    name: 'Contextual Action Suggestions',
    category: CardCategory.ImmediateAction,
    impactRating: 9,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Actionable cards: "Reply to Sarah," "Schedule follow-up"',
    keyValue: 'Reduces decision fatigue, direct action',
    intelligenceEnrichment: 'AI-drafted actions, adaptive suggestions',
    dataSources: ['Adaptive Cards', 'Bot Framework'],
    tags: ['actions', 'ai', 'suggestions'],
  },
  {
    id: 'cross-project-dependencies',
    catalogNumber: 68,
    name: 'Cross-Project Dependencies',
    category: CardCategory.ImmediateAction,
    impactRating: 9,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Implemented,
    existingCardId: 'organizationalHandoffMap',
    description: "Tasks blocked by or blocking other teams' work",
    keyValue: 'Organisational friction visibility',
    intelligenceEnrichment: 'Predicts cascade delays, suggests resolution paths',
    dataSources: ['Planner API', 'Project API'],
    tags: ['dependencies', 'blocking', 'cross-team'],
  },

  // ═══════════════════════════════════════════
  // PRODUCTIVITY PATTERNS (13 cards)
  // ═══════════════════════════════════════════
  {
    id: 'context-switch-counter',
    catalogNumber: 9,
    name: 'Context Switch Counter',
    category: CardCategory.ProductivityPatterns,
    impactRating: 9,
    minimumTier: LicenseTier.Individual,
    status: CardStatus.Implemented,
    existingCardId: 'contextSwitching',
    description: 'Projects/sites/teams touched today',
    keyValue: 'Awareness tool for cognitive load — the invisible tax',
    intelligenceEnrichment: 'Anomaly detection, adaptive personal thresholds',
    dataSources: ['SharePoint API', 'Teams API', 'Calendar API'],
    tags: ['focus', 'context-switching', 'cognitive-load'],
  },
  {
    id: 'focus-time-defender',
    catalogNumber: 10,
    name: 'Focus Time Defender',
    category: CardCategory.ProductivityPatterns,
    impactRating: 9,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'upcomingWeek',
    description: "Next week's calendar analyzed for fragmentation",
    keyValue: 'Proactive calendar hygiene before chaos hits',
    intelligenceEnrichment: 'Optimal reschedule suggestions',
    dataSources: ['Calendar API'],
    tags: ['focus', 'calendar', 'deep-work'],
  },
  {
    id: 'peak-productivity-windows',
    catalogNumber: 11,
    name: 'Peak Productivity Windows',
    category: CardCategory.ProductivityPatterns,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'When you complete tasks vs. when meetings are scheduled',
    keyValue: 'Self-knowledge for better scheduling decisions',
    intelligenceEnrichment: 'Adaptive pattern learning over time',
    dataSources: ['Calendar API', 'Planner API'],
    tags: ['productivity', 'scheduling', 'patterns'],
  },
  {
    id: 'deep-work-opportunities',
    catalogNumber: 12,
    name: 'Deep Work Opportunities',
    category: CardCategory.ProductivityPatterns,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Largest uninterrupted time blocks in next 5 days',
    keyValue: 'Helps protect what matters most',
    dataSources: ['Calendar API'],
    tags: ['focus', 'deep-work', 'calendar'],
  },
  {
    id: 'after-hours-footprint',
    catalogNumber: 13,
    name: 'After-Hours Footprint',
    category: CardCategory.ProductivityPatterns,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Evening/weekend activity trends with behavioral nudges',
    keyValue: 'Burnout prevention, boundary awareness',
    intelligenceEnrichment: 'Burnout prediction, trend anomalies',
    dataSources: ['Mail API', 'Teams API', 'Activity API'],
    tags: ['wellbeing', 'boundaries', 'after-hours'],
  },
  {
    id: 'task-completion-velocity',
    catalogNumber: 14,
    name: 'Task Completion Velocity',
    category: CardCategory.ProductivityPatterns,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'myTasks',
    description: 'How long tasks sit in to-do list before completion',
    keyValue: 'Calibration tool for realistic planning',
    intelligenceEnrichment: 'Predicts overdue risk per task',
    dataSources: ['Planner API', 'To Do API'],
    tags: ['tasks', 'velocity', 'planning'],
  },
  {
    id: 'meeting-preparation-gap',
    catalogNumber: 15,
    name: 'Meeting Preparation Gap',
    category: CardCategory.ProductivityPatterns,
    impactRating: 6,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: "Accepted meetings where you haven't opened related docs",
    keyValue: 'Accountability for meeting readiness',
    dataSources: ['Calendar API', 'OneDrive API'],
    tags: ['meetings', 'preparation'],
  },
  {
    id: 'email-response-patterns',
    catalogNumber: 16,
    name: 'Email Response Patterns',
    category: CardCategory.ProductivityPatterns,
    impactRating: 6,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Your typical response time by sender/urgency',
    keyValue: 'Helps set realistic expectations',
    dataSources: ['Mail API'],
    tags: ['email', 'response-time', 'patterns'],
  },
  {
    id: 'collaboration-overload-score',
    catalogNumber: 55,
    name: 'Collaboration Overload Score',
    category: CardCategory.ProductivityPatterns,
    impactRating: 9,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Scientifically validated metrics on meeting load, after-hours',
    keyValue: 'Research-backed burnout indicators',
    intelligenceEnrichment: 'Predictive burnout scoring, trend forecasting',
    dataSources: ['Viva Insights API'],
    tags: ['burnout', 'collaboration', 'overload'],
  },
  {
    id: 'collaboration-patterns',
    catalogNumber: 56,
    name: 'Collaboration Patterns',
    category: CardCategory.ProductivityPatterns,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'siteActivity',
    description: 'How you interact across teams and channels',
    keyValue: 'Network visibility and balance',
    dataSources: ['Teams API', 'SharePoint API'],
    tags: ['collaboration', 'network', 'patterns'],
  },
  {
    id: 'commitment-vs-capacity',
    catalogNumber: 69,
    name: 'Commitment vs. Capacity',
    category: CardCategory.ProductivityPatterns,
    impactRating: 9,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Task load across all projects vs. available time',
    keyValue: 'Overcommitment detection before burnout',
    intelligenceEnrichment: 'Predicts overcommitment 2 weeks out',
    dataSources: ['Planner API', 'Calendar API'],
    tags: ['capacity', 'overcommitment', 'planning'],
  },
  {
    id: 'seasonal-workload-prediction',
    catalogNumber: 75,
    name: 'Seasonal Workload Prediction',
    category: CardCategory.ProductivityPatterns,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Based on past years, when you typically get overwhelmed',
    keyValue: 'Proactive capacity planning',
    intelligenceEnrichment: 'ML-based seasonal forecasting',
    dataSources: ['Temporal Analysis'],
    tags: ['prediction', 'seasonal', 'capacity'],
  },
  {
    id: 'meeting-creep-trends',
    catalogNumber: 76,
    name: 'Meeting Creep Trends',
    category: CardCategory.ProductivityPatterns,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'How meeting load has changed over 6/12 months',
    keyValue: 'Before crisis becomes visible',
    intelligenceEnrichment: 'Trend extrapolation, tipping point alerts',
    dataSources: ['Calendar API', 'Temporal Analysis'],
    tags: ['meetings', 'trends', 'creep'],
  },

  // ═══════════════════════════════════════════
  // KNOWLEDGE MANAGEMENT (16 cards)
  // ═══════════════════════════════════════════
  {
    id: 'stale-documents',
    catalogNumber: 17,
    name: 'Stale Documents',
    category: CardCategory.KnowledgeManagement,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'recentFiles',
    description: 'Documents not updated in 90+ days still being referenced',
    keyValue: 'Prevents outdated information spreading',
    dataSources: ['SharePoint API', 'OneDrive API'],
    tags: ['documents', 'stale', 'knowledge'],
  },
  {
    id: 'siloed-knowledge',
    catalogNumber: 18,
    name: 'Siloed Knowledge',
    category: CardCategory.KnowledgeManagement,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Implemented,
    existingCardId: 'sharedWithMe',
    description: 'Critical docs only one person has accessed',
    keyValue: 'Bus factor risk identification',
    intelligenceEnrichment: 'Identifies knowledge concentration risks',
    dataSources: ['SharePoint API', 'Analytics API'],
    tags: ['silos', 'risk', 'knowledge-sharing'],
  },
  {
    id: 'document-version-conflicts',
    catalogNumber: 19,
    name: 'Document Version Conflicts',
    category: CardCategory.KnowledgeManagement,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Multiple versions of same-named docs in different locations',
    keyValue: 'Prevents confusion and rework',
    dataSources: ['SharePoint API', 'OneDrive API'],
    tags: ['versions', 'conflicts', 'documents'],
  },
  {
    id: 'knowledge-gap-detector',
    catalogNumber: 20,
    name: 'Knowledge Gap Detector',
    category: CardCategory.KnowledgeManagement,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Topics frequently asked about but poorly documented',
    keyValue: 'Guides documentation priorities',
    intelligenceEnrichment: 'NLP analysis of questions vs. docs',
    dataSources: ['Search API', 'Viva Topics API'],
    tags: ['gaps', 'documentation', 'questions'],
  },
  {
    id: 'recently-shared-externally',
    catalogNumber: 21,
    name: 'Recently Shared Externally',
    category: CardCategory.KnowledgeManagement,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Documents shared outside org in last 7 days',
    keyValue: 'External sharing awareness',
    dataSources: ['SharePoint API', 'OneDrive API'],
    tags: ['external', 'sharing', 'security'],
  },
  {
    id: 'expired-sharing-links',
    catalogNumber: 22,
    name: 'Expired Sharing Links',
    category: CardCategory.KnowledgeManagement,
    impactRating: 6,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'External links that have expired or should be reviewed',
    keyValue: 'Security hygiene maintenance',
    dataSources: ['SharePoint API'],
    tags: ['links', 'expired', 'security'],
  },
  {
    id: 'undiscoverable-content',
    catalogNumber: 23,
    name: 'Undiscoverable Content',
    category: CardCategory.KnowledgeManagement,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Content with poor metadata/tagging that never appears in search',
    keyValue: 'Improves content findability',
    dataSources: ['Search API', 'SharePoint API'],
    tags: ['search', 'metadata', 'findability'],
  },
  {
    id: 'wiki-freshness',
    catalogNumber: 24,
    name: 'Wiki Freshness',
    category: CardCategory.KnowledgeManagement,
    impactRating: 6,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Team wiki pages with stale content',
    keyValue: 'Keeps knowledge bases current',
    dataSources: ['SharePoint API', 'OneNote API'],
    tags: ['wiki', 'freshness', 'documentation'],
  },
  {
    id: 'meeting-notes-gap',
    catalogNumber: 25,
    name: 'Meeting Notes Gap',
    category: CardCategory.KnowledgeManagement,
    impactRating: 6,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Meetings without attached notes or recordings',
    keyValue: 'Institutional memory protection',
    dataSources: ['Calendar API', 'OneNote API', 'Stream API'],
    tags: ['meetings', 'notes', 'recording'],
  },
  {
    id: 'topic-expert-finder',
    catalogNumber: 58,
    name: 'Topic Expert Finder',
    category: CardCategory.KnowledgeManagement,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Who has deep expertise in topics you need help with',
    keyValue: 'Accelerates problem-solving',
    intelligenceEnrichment: 'ML-based expertise mapping',
    dataSources: ['Viva Topics API', 'Graph People API'],
    tags: ['experts', 'topics', 'help'],
  },
  {
    id: 'documentation-debt',
    catalogNumber: 59,
    name: 'Documentation Debt',
    category: CardCategory.KnowledgeManagement,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'High-traffic processes without documentation',
    keyValue: 'Reduces repeated questions',
    dataSources: ['SharePoint API', 'Analytics API'],
    tags: ['documentation', 'debt', 'processes'],
  },
  {
    id: 'orphaned-sites',
    catalogNumber: 60,
    name: 'Orphaned Sites',
    category: CardCategory.KnowledgeManagement,
    impactRating: 6,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'SharePoint sites with no recent activity',
    keyValue: 'Tenant hygiene and cost savings',
    dataSources: ['SharePoint Admin API'],
    tags: ['sites', 'orphaned', 'cleanup'],
  },
  {
    id: 'content-lifecycle-alerts',
    catalogNumber: 62,
    name: 'Content Lifecycle Alerts',
    category: CardCategory.KnowledgeManagement,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Documents approaching retention policy deadlines',
    keyValue: 'Compliance and archival awareness',
    dataSources: ['Compliance API', 'SharePoint API'],
    tags: ['lifecycle', 'retention', 'compliance'],
  },
  {
    id: 'cross-boundary-knowledge',
    catalogNumber: 64,
    name: 'Cross-Boundary Knowledge',
    category: CardCategory.KnowledgeManagement,
    impactRating: 8,
    minimumTier: LicenseTier.Leader,
    status: CardStatus.Placeholder,
    description: 'Valuable knowledge trapped in one department',
    keyValue: 'Org-wide knowledge leverage',
    intelligenceEnrichment: 'Cross-team knowledge mapping',
    dataSources: ['Viva Topics API', 'Graph API'],
    tags: ['cross-boundary', 'knowledge', 'sharing'],
  },
  {
    id: 'ai-knowledge-gaps',
    catalogNumber: 65,
    name: 'AI Knowledge Gaps',
    category: CardCategory.KnowledgeManagement,
    impactRating: 8,
    minimumTier: LicenseTier.Leader,
    status: CardStatus.Placeholder,
    description: 'Topics Copilot struggles with due to poor grounding',
    keyValue: 'Improves AI effectiveness',
    intelligenceEnrichment: 'Copilot performance analysis',
    dataSources: ['Copilot API', 'Search API'],
    tags: ['ai', 'copilot', 'grounding'],
  },
  {
    id: 'search-dead-ends',
    catalogNumber: 67,
    name: 'Search Dead Ends',
    category: CardCategory.KnowledgeManagement,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Frequent search queries with zero results',
    keyValue: 'Identifies content gaps',
    dataSources: ['Search Analytics API'],
    tags: ['search', 'gaps', 'queries'],
  },

  // ═══════════════════════════════════════════
  // COLLABORATION HEALTH (13 cards)
  // ═══════════════════════════════════════════
  {
    id: 'communication-debt',
    catalogNumber: 26,
    name: 'Communication Debt',
    category: CardCategory.CollaborationHealth,
    impactRating: 9,
    minimumTier: LicenseTier.Individual,
    status: CardStatus.Placeholder,
    description: 'Colleagues you owe responses to',
    keyValue: 'Relationship maintenance at scale',
    dataSources: ['Mail API', 'Teams API'],
    tags: ['communication', 'debt', 'relationships'],
  },
  {
    id: 'team-connectivity-gaps',
    catalogNumber: 27,
    name: 'Team Connectivity Gaps',
    category: CardCategory.CollaborationHealth,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Team members with declining interaction',
    keyValue: 'Early warning for team cohesion',
    intelligenceEnrichment: 'Trend analysis, isolation detection',
    dataSources: ['Teams API', 'Mail API'],
    tags: ['team', 'connectivity', 'isolation'],
  },
  {
    id: 'relationship-strength-tracker',
    catalogNumber: 28,
    name: 'Relationship Strength Tracker',
    category: CardCategory.CollaborationHealth,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'myTeam',
    description: 'Key relationships and how strong they are',
    keyValue: 'Proactive relationship management',
    dataSources: ['Mail API', 'Teams API', 'Calendar API'],
    tags: ['relationships', 'strength', 'network'],
  },
  {
    id: 'network-periphery',
    catalogNumber: 29,
    name: 'Network Periphery',
    category: CardCategory.CollaborationHealth,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'People at the edges of your network who might be valuable',
    keyValue: 'Expands strategic connections',
    dataSources: ['Graph People API', 'Teams API'],
    tags: ['network', 'periphery', 'connections'],
  },
  {
    id: 'declining-relationships',
    catalogNumber: 30,
    name: 'Declining Relationships',
    category: CardCategory.CollaborationHealth,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Previously strong connections now fading',
    keyValue: 'Prevents accidental relationship decay',
    dataSources: ['Mail API', 'Teams API', 'Calendar API'],
    tags: ['relationships', 'declining', 'maintenance'],
  },
  {
    id: 'new-joiner-integration',
    catalogNumber: 31,
    name: 'New Joiner Integration',
    category: CardCategory.CollaborationHealth,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'How well new team members are connecting',
    keyValue: 'Onboarding effectiveness tracking',
    intelligenceEnrichment: 'Benchmark against successful integrations',
    dataSources: ['Graph API', 'Teams API'],
    tags: ['onboarding', 'new-joiners', 'integration'],
  },
  {
    id: 'cross-team-bridges',
    catalogNumber: 32,
    name: 'Cross-Team Bridges',
    category: CardCategory.CollaborationHealth,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Your connections that span team boundaries',
    keyValue: 'Strategic network awareness',
    dataSources: ['Graph API', 'Teams API'],
    tags: ['cross-team', 'bridges', 'network'],
  },
  {
    id: 'org-network-position',
    catalogNumber: 33,
    name: 'Org Network Position',
    category: CardCategory.CollaborationHealth,
    impactRating: 7,
    minimumTier: LicenseTier.Leader,
    status: CardStatus.Placeholder,
    description: 'Your position in the organisational network graph',
    keyValue: 'Strategic influence awareness',
    intelligenceEnrichment: 'Centrality and brokerage analysis',
    dataSources: ['Graph Analytics API'],
    tags: ['network', 'position', 'influence'],
  },
  {
    id: 'meeting-quality-score',
    catalogNumber: 34,
    name: 'Meeting Quality Score',
    category: CardCategory.CollaborationHealth,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Engagement signals from your meetings',
    keyValue: 'Meeting effectiveness feedback',
    dataSources: ['Teams Meeting API', 'Attendance API'],
    tags: ['meetings', 'quality', 'engagement'],
  },
  {
    id: 'response-time-expectations',
    catalogNumber: 70,
    name: 'Response Time Expectations',
    category: CardCategory.CollaborationHealth,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Calibrate expectations with frequent collaborators',
    keyValue: 'Reduces friction from mismatched expectations',
    dataSources: ['Mail API', 'Teams API'],
    tags: ['response-time', 'expectations', 'calibration'],
  },
  {
    id: 'organisational-silos',
    catalogNumber: 71,
    name: 'Organisational Silos',
    category: CardCategory.CollaborationHealth,
    impactRating: 8,
    minimumTier: LicenseTier.Leader,
    status: CardStatus.Placeholder,
    description: 'Teams that rarely interact but should',
    keyValue: 'Org-level collaboration opportunities',
    intelligenceEnrichment: 'Silo detection and bridge suggestions',
    dataSources: ['Graph Analytics API', 'Teams API'],
    tags: ['silos', 'collaboration', 'org-level'],
  },
  {
    id: 'unusual-activity-patterns',
    catalogNumber: 78,
    name: 'Unusual Activity Patterns',
    category: CardCategory.CollaborationHealth,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Work patterns deviating significantly from your norm',
    keyValue: 'Burnout signals, security concerns',
    intelligenceEnrichment: 'Anomaly detection with adaptive baselines',
    dataSources: ['Activity API', 'Temporal Analysis'],
    tags: ['anomaly', 'patterns', 'burnout'],
  },
  {
    id: 'calendar-politics',
    catalogNumber: 77,
    name: 'Calendar Politics',
    category: CardCategory.CollaborationHealth,
    impactRating: 6,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Who schedules over your focus time',
    keyValue: 'Identifies calendar boundary violators',
    dataSources: ['Calendar API'],
    tags: ['calendar', 'politics', 'boundaries'],
  },

  // ═══════════════════════════════════════════
  // MANAGER TOOLKIT (13 cards)
  // ═══════════════════════════════════════════
  {
    id: 'team-workload-balance',
    catalogNumber: 35,
    name: 'Team Workload Balance',
    category: CardCategory.ManagerToolkit,
    impactRating: 9,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Workload distribution across direct reports',
    keyValue: 'Prevents burnout and resentment',
    dataSources: ['Planner API', 'Calendar API', 'Teams API'],
    tags: ['team', 'workload', 'balance'],
  },
  {
    id: 'one-on-one-gaps',
    catalogNumber: 36,
    name: '1:1 Gaps',
    category: CardCategory.ManagerToolkit,
    impactRating: 9,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Direct reports without recent 1:1 meetings',
    keyValue: 'Manager accountability for face time',
    dataSources: ['Calendar API'],
    tags: ['one-on-one', 'gaps', 'management'],
  },
  {
    id: 'team-availability',
    catalogNumber: 37,
    name: 'Team Availability',
    category: CardCategory.ManagerToolkit,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Who on your team is available when',
    keyValue: 'Scheduling and coverage planning',
    dataSources: ['Calendar API', 'Presence API'],
    tags: ['team', 'availability', 'scheduling'],
  },
  {
    id: 'recognition-gaps',
    catalogNumber: 38,
    name: 'Recognition Gaps',
    category: CardCategory.ManagerToolkit,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Team members without recent recognition',
    keyValue: 'Prevents recognition blind spots',
    intelligenceEnrichment: 'Suggests recognition moments',
    dataSources: ['Viva Engage API', 'Mail API'],
    tags: ['recognition', 'team', 'engagement'],
  },
  {
    id: 'delegation-opportunities',
    catalogNumber: 39,
    name: 'Delegation Opportunities',
    category: CardCategory.ManagerToolkit,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Tasks you could delegate based on team capacity',
    keyValue: 'Manager time reclaim',
    intelligenceEnrichment: 'Skill-matched delegation suggestions',
    dataSources: ['Planner API', 'Calendar API'],
    tags: ['delegation', 'capacity', 'management'],
  },
  {
    id: 'team-meeting-burden',
    catalogNumber: 40,
    name: 'Team Meeting Burden',
    category: CardCategory.ManagerToolkit,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Which team members are in meeting overload',
    keyValue: 'Protects team productivity',
    dataSources: ['Calendar API'],
    tags: ['meetings', 'burden', 'team'],
  },
  {
    id: 'succession-risk',
    catalogNumber: 41,
    name: 'Succession Risk',
    category: CardCategory.ManagerToolkit,
    impactRating: 9,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Critical knowledge held by single team members',
    keyValue: 'Risk mitigation and planning',
    intelligenceEnrichment: 'Knowledge concentration analysis',
    dataSources: ['SharePoint API', 'Graph API'],
    tags: ['succession', 'risk', 'knowledge'],
  },
  {
    id: 'team-collaboration-health',
    catalogNumber: 42,
    name: 'Team Collaboration Health',
    category: CardCategory.ManagerToolkit,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'How well your team collaborates internally',
    keyValue: 'Team cohesion monitoring',
    dataSources: ['Teams API', 'Mail API'],
    tags: ['team', 'collaboration', 'health'],
  },
  {
    id: 'career-development-signals',
    catalogNumber: 43,
    name: 'Career Development Signals',
    category: CardCategory.ManagerToolkit,
    impactRating: 7,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Team members showing growth or stagnation',
    keyValue: 'Proactive career conversations',
    intelligenceEnrichment: 'Skill development pattern analysis',
    dataSources: ['Viva Learning API', 'Project API'],
    tags: ['career', 'development', 'growth'],
  },
  {
    id: 'attrition-risk-signals',
    catalogNumber: 44,
    name: 'Attrition Risk Signals',
    category: CardCategory.ManagerToolkit,
    impactRating: 9,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Behavioral patterns indicating flight risk',
    keyValue: 'Early intervention opportunity',
    intelligenceEnrichment: 'ML-based attrition prediction',
    dataSources: ['Activity API', 'Calendar API', 'Teams API'],
    tags: ['attrition', 'risk', 'retention'],
  },
  {
    id: 'skip-level-visibility',
    catalogNumber: 57,
    name: 'Skip-Level Visibility',
    category: CardCategory.ManagerToolkit,
    impactRating: 7,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Activity and engagement of skip-level reports',
    keyValue: 'Extended team awareness',
    dataSources: ['Graph API', 'Teams API'],
    tags: ['skip-level', 'visibility', 'team'],
  },
  {
    id: 'team-learning-velocity',
    catalogNumber: 72,
    name: 'Team Learning Velocity',
    category: CardCategory.ManagerToolkit,
    impactRating: 7,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'How quickly your team is acquiring new skills',
    keyValue: 'L&D investment tracking',
    dataSources: ['Viva Learning API'],
    tags: ['learning', 'team', 'development'],
  },
  {
    id: 'team-sentiment-tracker',
    catalogNumber: 79,
    name: 'Team Sentiment Tracker',
    category: CardCategory.ManagerToolkit,
    impactRating: 8,
    minimumTier: LicenseTier.Manager,
    status: CardStatus.Placeholder,
    description: 'Aggregate sentiment from team communications',
    keyValue: 'Early culture warning system',
    intelligenceEnrichment: 'NLP sentiment analysis',
    dataSources: ['Teams API', 'Viva Engage API'],
    tags: ['sentiment', 'team', 'culture'],
  },

  // ═══════════════════════════════════════════
  // GOVERNANCE & COMPLIANCE (14 cards)
  // ═══════════════════════════════════════════
  {
    id: 'overshared-documents',
    catalogNumber: 45,
    name: 'Overshared Documents',
    category: CardCategory.GovernanceCompliance,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Documents shared more broadly than necessary',
    keyValue: 'Security posture improvement',
    dataSources: ['SharePoint API', 'DLP API'],
    tags: ['oversharing', 'security', 'documents'],
  },
  {
    id: 'sensitive-file-access',
    catalogNumber: 46,
    name: 'Sensitive File Access',
    category: CardCategory.GovernanceCompliance,
    impactRating: 9,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Recent access to files with sensitivity labels',
    keyValue: 'Audit and awareness',
    dataSources: ['SharePoint API', 'Sensitivity Labels API'],
    tags: ['sensitive', 'access', 'audit'],
  },
  {
    id: 'permission-anomalies',
    catalogNumber: 47,
    name: 'Permission Anomalies',
    category: CardCategory.GovernanceCompliance,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Unusual permission grants or access patterns',
    keyValue: 'Security incident prevention',
    dataSources: ['SharePoint API', 'Azure AD API'],
    tags: ['permissions', 'anomalies', 'security'],
  },
  {
    id: 'expiring-guest-access',
    catalogNumber: 48,
    name: 'Expiring Guest Access',
    category: CardCategory.GovernanceCompliance,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Guest user access approaching expiry',
    keyValue: 'Access continuity management',
    dataSources: ['Azure AD API', 'SharePoint API'],
    tags: ['guest', 'access', 'expiry'],
  },
  {
    id: 'compliance-training-due',
    catalogNumber: 49,
    name: 'Compliance Training Due',
    category: CardCategory.GovernanceCompliance,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Required training modules approaching deadline',
    keyValue: 'Compliance deadline awareness',
    dataSources: ['Viva Learning API'],
    tags: ['training', 'compliance', 'deadlines'],
  },
  {
    id: 'dlp-policy-violations',
    catalogNumber: 50,
    name: 'DLP Policy Violations',
    category: CardCategory.GovernanceCompliance,
    impactRating: 9,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Recent DLP policy triggers from your activity',
    keyValue: 'Personal compliance awareness',
    dataSources: ['DLP API', 'Compliance Center API'],
    tags: ['dlp', 'violations', 'compliance'],
  },
  {
    id: 'retention-action-required',
    catalogNumber: 51,
    name: 'Retention Action Required',
    category: CardCategory.GovernanceCompliance,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Content requiring review before retention deletion',
    keyValue: 'Data governance participation',
    dataSources: ['Retention API', 'SharePoint API'],
    tags: ['retention', 'review', 'governance'],
  },
  {
    id: 'shadow-it-detection',
    catalogNumber: 52,
    name: 'Shadow IT Detection',
    category: CardCategory.GovernanceCompliance,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Unapproved apps being used for work',
    keyValue: 'Security and compliance risk awareness',
    dataSources: ['Cloud App Security API'],
    tags: ['shadow-it', 'apps', 'security'],
  },
  {
    id: 'personal-data-exposure',
    catalogNumber: 53,
    name: 'Personal Data Exposure',
    category: CardCategory.GovernanceCompliance,
    impactRating: 9,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'PII detected in your documents',
    keyValue: 'GDPR/privacy compliance',
    dataSources: ['DLP API', 'Content Search API'],
    tags: ['pii', 'privacy', 'gdpr'],
  },
  {
    id: 'access-review-pending',
    catalogNumber: 54,
    name: 'Access Review Pending',
    category: CardCategory.GovernanceCompliance,
    impactRating: 7,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Access reviews requiring your action',
    keyValue: 'Timely access governance',
    dataSources: ['Identity Governance API'],
    tags: ['access-review', 'governance', 'identity'],
  },
  {
    id: 'compliance-posture-score',
    catalogNumber: 61,
    name: 'Compliance Posture Score',
    category: CardCategory.GovernanceCompliance,
    impactRating: 8,
    minimumTier: LicenseTier.Leader,
    status: CardStatus.Placeholder,
    description: 'Aggregate compliance health across your scope',
    keyValue: 'Executive compliance visibility',
    dataSources: ['Compliance Manager API'],
    tags: ['compliance', 'posture', 'score'],
  },
  {
    id: 'data-residency-violations',
    catalogNumber: 63,
    name: 'Data Residency Violations',
    category: CardCategory.GovernanceCompliance,
    impactRating: 9,
    minimumTier: LicenseTier.Leader,
    status: CardStatus.Placeholder,
    description: 'Data stored outside allowed regions',
    keyValue: 'Regulatory compliance',
    dataSources: ['Azure Policy API', 'SharePoint API'],
    tags: ['data-residency', 'regions', 'compliance'],
  },
  {
    id: 'third-party-app-risk',
    catalogNumber: 73,
    name: 'Third-Party App Risk',
    category: CardCategory.GovernanceCompliance,
    impactRating: 8,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Placeholder,
    description: 'Connected apps with excessive permissions',
    keyValue: 'App permission hygiene',
    dataSources: ['Azure AD API', 'App Governance API'],
    tags: ['apps', 'permissions', 'risk'],
  },
  {
    id: 'eol-system-dependencies',
    catalogNumber: 74,
    name: 'EOL System Dependencies',
    category: CardCategory.GovernanceCompliance,
    impactRating: 7,
    minimumTier: LicenseTier.Leader,
    status: CardStatus.Placeholder,
    description: 'Dependencies on end-of-life systems',
    keyValue: 'Technical debt visibility',
    dataSources: ['Azure API', 'Custom Inventory'],
    tags: ['eol', 'dependencies', 'technical-debt'],
  },

  // ═══════════════════════════════════════════
  // UTILITY CARD (not in spec, but implemented)
  // ═══════════════════════════════════════════
  {
    id: 'quick-links',
    catalogNumber: 80, // Custom number for utility
    name: 'Quick Links',
    category: CardCategory.KnowledgeManagement,
    impactRating: 5,
    minimumTier: LicenseTier.Team,
    status: CardStatus.Implemented,
    existingCardId: 'quickLinks',
    description: 'Frequently accessed links and bookmarks',
    keyValue: 'Quick access to important resources',
    dataSources: ['SharePoint API', 'Custom Links'],
    tags: ['links', 'bookmarks', 'navigation'],
  },
];

// ═══════════════════════════════════════════
// Helper Functions
// ═══════════════════════════════════════════

/**
 * Get card by ID
 */
export function getCardById(id: string): CardRegistration | undefined {
  return CARD_REGISTRY.find((card) => card.id === id);
}

/**
 * Get card by legacy ID
 */
export function getCardByLegacyId(legacyId: string): CardRegistration | undefined {
  return CARD_REGISTRY.find((card) => card.existingCardId === legacyId);
}

/**
 * Get cards by category
 */
export function getCardsByCategory(category: CardCategory): CardRegistration[] {
  return CARD_REGISTRY.filter((card) => card.category === category);
}

/**
 * Get cards by minimum tier
 */
export function getCardsByMinimumTier(tier: LicenseTier): CardRegistration[] {
  return CARD_REGISTRY.filter((card) => card.minimumTier === tier);
}

/**
 * Get cards by status
 */
export function getCardsByStatus(status: CardStatus): CardRegistration[] {
  return CARD_REGISTRY.filter((card) => card.status === status);
}

/**
 * Get implemented cards
 */
export function getImplementedCards(): CardRegistration[] {
  return getCardsByStatus(CardStatus.Implemented);
}

/**
 * Get placeholder cards
 */
export function getPlaceholderCards(): CardRegistration[] {
  return getCardsByStatus(CardStatus.Placeholder);
}

/**
 * Get total card count
 */
export function getTotalCardCount(): number {
  return CARD_REGISTRY.length;
}

/**
 * Get card count by category
 */
export function getCardCountByCategory(): Record<CardCategory, number> {
  const counts: Record<CardCategory, number> = {
    [CardCategory.ImmediateAction]: 0,
    [CardCategory.ProductivityPatterns]: 0,
    [CardCategory.KnowledgeManagement]: 0,
    [CardCategory.CollaborationHealth]: 0,
    [CardCategory.ManagerToolkit]: 0,
    [CardCategory.GovernanceCompliance]: 0,
  };

  CARD_REGISTRY.forEach((card) => {
    counts[card.category]++;
  });

  return counts;
}
