define([], function() {
  return {
    "PropertyPaneDescription": "Configure your dashboard settings",
    "BasicGroupName": "Display Settings",
    "GreetingGroupName": "Greeting",
    "DescriptionFieldLabel": "Description Field",
    "SalutationTypeLabel": "Style",
    "SalutationTimeBased": "Time-based (Good morning/afternoon/evening)",
    "SalutationWorldHello": "World Hello (rotating languages)",
    "SalutationClaude": "Friendly greeting",
    "SalutationNone": "No greeting",
    "SalutationSizeLabel": "Size",
    "SalutationSizeH1": "Title 1 (28px)",
    "SalutationSizeH2": "Title 2 (24px)",
    "SalutationSizeH3": "Title 3 (20px)",
    "SalutationSizeH4": "Subtitle 1 (20px semibold)",
    "SalutationSizeH5": "Subtitle 2 (16px semibold)",
    "CardsGroupName": "Cards",
    "CardVisible": "Visible",
    "CardHidden": "Hidden",
    "CardTodaysAgenda": "Today's Agenda",
    "CardUnreadInbox": "Unread Inbox",
    "CardMyTasks": "My Tasks",
    "CardRecentFiles": "Recent Files",
    "CardUpcomingWeek": "Upcoming Week",
    "CardFlaggedEmails": "Flagged Emails",
    "CardMyTeam": "My Team",
    "CardSharedWithMe": "Shared With Me",
    "CardQuickLinks": "Quick Links",
    "CardSiteActivity": "Site Activity",
    "CardOrderGroupName": "Card Order",
    "CardOrderLabel": "Toggle visibility and drag to reorder",
    "ConfigureCardsButton": "Configure Cards...",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});